### ISSUE TITLE
Upgrade to Picocli 3.0.0

### ISSUE THREAD

**Issue by kakawait** [kakawait/picocli-spring-boot-starter#2]
- [ ] Rework _version_ and _help_ display https://github.com/remkop/picocli/issues/162 https://github.com/remkop/picocli/issues/145
- [ ] Consider https://github.com/remkop/picocli/issues/157 could be useful
- [x] Support _subcommand_ https://github.com/remkop/picocli/issues/152 (see #12)

**Comment by bobtiernay-okta** [comment]
Any chance of upgrading to 3.0.0?

**Comment by kakawait** [comment]
If released yes i will directly upgrade to latest.

**Comment by kakawait** [comment]
@bobtiernay-okta I just created a new branch [`picocli-3.0.0`](https://github.com/kakawait/picocli-spring-boot-starter/tree/picocli-3.0.0) where I upgrade `picocli` dep to `3.0.0-beta-1` (latest version in _maven central_, I will upgrade to `beta-2` as soon as is will be available on _maven central_)

In addition I pushed the artifact with version

```xml
<dependency>
    <groupId>com.kakawait</groupId>
    <artifactId>picocli-spring-boot-starter</artifactId>
    <version>1.0.0-alpha-1</version>
</dependency>
```

**Be careful** I just pushed can take some time before available on _maven central_

Why `alpha`?

For two main reasons:

1. Not heavily tested
2. Not specific integration (in order to take advantage of new things/features), just upgraded deps and fix compilation/runtime issues 

---

Please if you have any issue (if you have time to test) report it.

Currently I'm working on other of my open sourced starter to get _Spring boot 2_ support, then I will focus on that starter
